init: initial commit with first additions
vfcgroup/docs pull request #1
Opened 2023-04-09 05:53 UTC by starfayer

First additions
Added books, courses, links
Content can be rearranged with groups

2023-04-09 07:27 UTC, igsekor requested changes
Большое спасибо! Хорошая работа! Внёс свои правки и поредачил.

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Пожалуй, наиболее хороший и доступный курс для самостоятельного изучения фронтенд-разработке. Имеет большое кол-во практических заданий (не надо пытаться выполнить все) и сообщество единомышленников.
```suggestion
Курс для самостоятельного изучения фронтенд-разработки. Имеет большое количество практических заданий (не надо пытаться выполнить всё) и сообщество единомышленников. При хорошей учёбе дают ментора.
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Сайт, на котором собрано большое кол-во курсов или книг. Чтобы получить пользу, придётся потратить на это время.
```suggestion
Сайт, на котором собрано большое количество курсов или книг. Чтобы получить пользу, придётся потратить на это время.
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +1. [RS School](https://rs.school/)
```suggestion

1. [RS School](https://rs.school/)  
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Github страница, на которой бесплатно собран список курсов и план, по которому можно изучать computer science в целом. Есть лекции и проекты, для общего развития.
```suggestion
GitHub страница, на которой собран список курсов и план, по которому можно изучать Computer Science в целом. Есть лекции и проекты, для общего развития.
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +3. [Открытый университет Open Culture](https://www.openculture.com/)
```suggestion
3. [Открытый университет Open Culture](https://www.openculture.com/)

```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +2. [Открытый университет OSSU](https://github.com/ossu/computer-science)
```suggestion
2. [Открытый университет OSSU](https://github.com/ossu/computer-science)

```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +## Статьи, видеолекции
```suggestion
## Статьи, видеолекции

```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Статьи и лекции могут содержать описание в своем названии.
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Вам не нравится vim вплоть до того момента, пока вы не начинаете его использовать. Лекция недолгая, но это может стоить того.
```suggestion
```

Кажется, что не надо делать эти комментарии. И так всё понятно в комментариях

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Мы привыкли писать в ООП. Однако данная лекция и ряд материалов далее поясняет об ином подходе. Он не лучше или хуже, он другой.
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +3. [Функциональный подход в программировании, Роберт Мартин (книга Чистый код](https://www.youtube.com/watch?v=7Zlp9rKHGD4)
```suggestion
3. [Функциональный подход в программировании, Роберт Мартин (по книге Чистый код)](https://www.youtube.com/watch?v=7Zlp9rKHGD4)
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Тяжелая статья от разработчика фреймворка [Solid.js](https://www.solidjs.com/) про компиляцию фреймворков.
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +## Авторы
```suggestion
## Авторы

```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Хороший автор, у которого интересно читать доклады об архитектуре и опыт разработки.
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +1. [bespoyasov.ru](https://bespoyasov.ru/)
```suggestion
1. Саша Беспоясов — [bespoyasov.ru](https://bespoyasov.ru/)
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +## Практика
```suggestion
## Практика

```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Проекты для портфолио на разных языках, ссылки на книги и ресурсы. Можно найти интересную задачу и через практику изучить язык, а также известную технологию под капотом (например, изучение и написани
```suggestion
1. [project-based-learning. Практические проекты на разных языках](https://github.com/practical-tutorials/project-based-learning) — Проекты для портфолио на разных языках, ссылки на книги и ресурсы. Можно найти интересную задачу и через практику изучить язык, а также известную технологию под капотом (например, изучение и написание компилятора).
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Ещё один репозиторий для практики с большим кол-вом звёздочек на github.
```suggestion
2. [build-your-own-x. Практические проекты на разных языках](https://github.com/codecrafters-io/build-your-own-x) — Репозиторий для практики с большим кол-вом звёздочек на GitHub.
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +## Ресурсы, инструменты
```suggestion
## Ресурсы, инструменты

```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +Выручает, когда нужно использовать API для погоды или новостей в своих пет-проектах.
```suggestion
1. [performance-checklist](https://github.com/thedaviddias/Front-End-Performance-Checklist) — Не совсем статья, скорее набор знаний о том, как при использовании разных инструментов учитывать их производительность.
2. [awesome list](https://github.com/sindresorhus/awesome)  
3. [public apis. Бесплатные сервисы для использования в своих проектах](https://github.com/public-apis/public-apis) — Выручает, когда нужно использовать API для погоды или новостей в своих пет-проектах.
```

2023-04-09 07:27 UTC, igsekor commented on materials/courses.md
> +![courses](../images/courses.jpg)
```suggestion
```
Предлагаю всё таки не добавлять картинку. Лучше просто текст.

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +![library](../images/library.jpg)
```suggestion
```
Предлагаю не внедрять картинки в списки :)

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +---
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +## Общие положения о программировании
```suggestion
## Общее о программировании

```

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +1. ***С. Макконелл, "Совершенный код".***
```suggestion
1. **[С. Макконелл «Совершенный код. Практическое руководство по разработке программного обеспечения»](https://bhv.ru/product/sovershennyj-kod/).** (перевод, оригинал «[Code Complete, 2nd Edition](https://www.microsoftpressstore.com/store/code-complete-9780735619678)»)
```

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +Книга содержит ссылки на другие книги определенных тематик, на что также рекомендую обратить внимание.
```suggestion
```

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +Есть противоречивые комментарии по поводу этой книги, лучше ознакомиться с ней лично и, скорее всего, не делать выводов по отзывам...
```suggestion
2. **[Р. Мартин, «Чистый код: создание, анализ и рефакторинг. Библиотека программиста»](https://www.piter.com/product/chistyy-kod-sozdanie-analiz-i-refaktoring-biblioteka-programmista-45ccca)** (перевод, оригинал «[Clean Code: A Handbook of Agile Software Craftsmanship](https://www.pearson.de/clean-code-a-handbook-of-agile-software-craftsmanship-9780136083221)»)
```

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +Книга содержит ссылки на другие книги определенных тематик, на что также рекомендую обратить внимание.
```suggestion
```

Репозиторий сообщества у нас публичный, поэтому личные комментарии не очень хороши

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +3. ***В. Феррейра, "Теоретический минимум по Computer Science"***
```suggestion
3. **[В. Фило «Теоретический минимум по Computer Science. Все что нужно программисту и разработчику»](https://www.piter.com/collection/all/product/teoreticheskiy-minimum-po-computer-science-vse-chto-nuzhno-programmistu-i-razrabotchiku)** (перевод, оригинал «[Computer Science Distilled: Learn the Art of Solving Computational Problems](https://code.energy/computer-science-distilled/)»)
```

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +`TODO`
```suggestion
```
Давайте просто не писать разделы, которых нет пока 😇

2023-04-09 07:27 UTC, igsekor commented on materials/library.md
> +Книга для популярного чтения, кажется, что есть более серьезные пособия
```suggestion
1. **[Р. Стивенс «Алгоритмы. Теория и практическое применение. 2-е издание»](https://eksmo.ru/book/algoritmy-teoriya-i-prakticheskoe-primenenie-2-e-izdanie-ITD1210854/)** (перевод, оригинал «[Essential Algorithms: A Practical Approach to Computer Algorithms](https://www.wiley.com/en-us/Essential+Algorithms%3A+A+Practical+Approach+to+Computer+Algorithms-p-9781118797297)»)
2. **[А. Бхаргава «Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих»](https://www.piter.com/collection/all/product/grokaem-algoritmy-illyustrirovannoe-posobie-dlya-programmistov-i-lyubopytstvuyuschih-2)** (перевод, оригинал «[Grokking Algorithms. An illustrated guide for programmers and other curious people](https://www.manning.com/books/grokking-algorithms)»)
```

2023-04-09 07:39 UTC, denisputnov approved these changes

2023-04-09 15:55 UTC, starfayer reviewed
Подтверждаю изменения

2023-04-09 16:00 UTC, starfayer reviewed
Подтвердил файлы в изменении

2023-04-09 16:32 UTC, igsekor commented
Примите, пожалуйста, все предложения или жду Ваших. Ну и картинки нужно удалить.

2023-04-10 08:07 UTC, starfayer commented
Вручную сделал коммит с принятыми изменениями

2023-04-10 08:09 UTC, starfayer commented on materials/courses.md
> +Вам не нравится vim вплоть до того момента, пока вы не начинаете его использовать. Лекция недолгая, но это может стоить того.
Все комментарии существуют для привлечения внимания. Знаю людей, которым vim не предпочтителен, поэтому это могло бы побудить новых разработчиков поизучать этот инструмент...

2023-04-10 08:51 UTC, igsekor approved these changes
Ну вот так вроде ничего получается :)

2023-04-10 08:51 UTC, igsekor commented on materials/library.md
> +## Общее о программировании
```suggestion
## Общее о программировании

```

2023-04-10 08:51 UTC, igsekor commented on materials/library.md
> +## Алгоритмы
```suggestion
## Алгоритмы

```

2023-04-10 08:52 UTC, merged